### ISSUE TITLE
Configuration if Nginx also running in container

### ISSUE THREAD

**Issue by JoLander** [schenkd/nginx-ui#12]
Can you give an example of the docker startup command or the docker-compose.yml if the nginx instance also running in a docker container.
How can we link both containers?

**Comment by maese83** [comment]
Hi, thx for the nice UI!
For me it would be also helpfull that I can run nginx-ui out of docker-compose.yml. 

I tried to map the volume  ./nginx/**sites-available**:/etc/nginx/conf.d. But it does not recongnize the subfolder/files in there. In /nginx/sites-available I have the different .conf files in subfolders like 1_dev/site1.conf, 2_test/site1.conf, 3_prod/site1.conf.

Would be nice if this would work with your tool

**Comment by debuggerboy** [comment]
> Can you give an example of the docker startup command or the docker-compose.yml if the nginx instance also running in a docker container.
> How can we link both containers?

Can you try the `docker-compose.yml` snippet : https://github.com/schenkd/nginx-ui#docker 

You might have to use the above snippet inside an existing `docker-compose.yml` with nginx and use along side.

**Comment by schenkd** [comment]
Hello @JoLander, an example is already in the project for docker-compose. It is important that you mount the directory of nginx (/etc/nginx) in the same place as in nginx-ui (/etc/nginx) . Does this help you? 

```yaml
version: '3'
services:
  nginx-ui:
    container_name: nginx-ui
    build: .
    image: nginx-ui:latest
    ports:
      - 8080:8080
    volumes:
      - nginx:/etc/nginx

  nginx:
    container_name: nginx
    image: nginx:1.18.0-alpine
    ports:
      - 80:80
    volumes:
      - nginx:/etc/nginx

volumes:
  nginx:
```
