### ISSUE TITLE
Support for arm64?

### ISSUE THREAD

**Issue by ha1fdan** [schenkd/nginx-ui#48]
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested.

**Can you somehow add support for arm64?**

**Comment by zhubby** [comment]
need arm64

**Comment by mohamedtaee** [comment]
@ha1fdan @zhubby how are you trying to run this? It should build based on your host platform, but you can probably force the platform in the docker-compose.yml like the snippet below.
```yml
version: '3'
services:
  flask-nginx-ui:
    container_name: flask-nginx-ui
    build:
      context: .
      dockerfile: Dockerfile
    image: flask-nginx-ui:latest
    platform: linux/arm64
    ports:
      - "8080:8080"
    volumes:
      - nginx:/etc/nginx

  nginx:
    container_name: nginx
    image: nginx:alpine3.19
    platform: linux/arm64
    ports:
      - "443:443"
    volumes:
      - nginx:/etc/nginx

volumes:
  nginx:
```

Also, feel free to follow my fork and I can help: https://github.com/mohamedtaee/nginx-ui
