### ISSUE TITLE
/static/themes missing on manual build

### ISSUE THREAD

**Issue by mattheys** [schenkd/nginx-ui#9]
I'm running on Aarch64 so had to build from source as you only seem to have Arm64 containers.

```
  nginxui:
    container_name: nginxui
    build: https://github.com/schenkd/nginx-ui.git
    volumes:
      - /opt/nginx:/etc/nginx
    restart: unless-stopped
    networks:
      - internal
```

However there is no content in the /static/themes folder in the web app, these means the outline-icons aren't loaded.
